/*

 FLOOR16MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\19082\Desktop\gbtd\AStar\Floor16.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Floor16MapWidth 20
#define Floor16MapHeight 18
#define Floor16MapBank 0

extern unsigned char Floor16Map[];

/* End of FLOOR16MAP.H */
